export enum IconNames {
  AcademicCap = 'academic-cap',
  Adjustments = 'adjustments',
  Annotation = 'annotation',
  Archive = 'archive',
  ArrowCircleDown = 'arrow-circle-down',
  ArrowCircleLeft = 'arrow-circle-left',
  ArrowCircleRight = 'arrow-circle-right',
  ArrowCircleUp = 'arrow-circle-up',
  ArrowDown = 'arrow-down',
  ArrowLeft = 'arrow-left',
  Check = 'check',
  ExclamationCircle = 'exclamation-circle',
  Exclamation = 'exclamation',
  Eye = 'eye',
  EyeOff = 'eye-off',
  Plus = 'plus',
  ShieldExclamation = 'shield-exclamation',
  XCircle = 'xcircle',
  X = 'x',
}
